"""Settings and input models for the Solace lighting engine.

PURE MODULE — no ``homeassistant`` imports.

Implements the 2026-08-15 Master Processing vs Post Processing architecture:
- Master Processing: Spline Lux demand + Cloudy Boost, 24h Brightness timeline, 24h Colour timeline
- Post Processing: State Table (L1, L2, L3, Ls, Off), Stops bias hierarchy, Bedroom Special Modes,
  hardware clamps, explicit Auto/Manual state, and 8 softcoded transitions.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from enum import Enum

from .spline import SplinePoint

__all__ = [
    "Family",
    "ZoneSettings",
    "Mode",
    "RampPoint",
    "SplinePoint",
    "MasterOutput",
    "StateTable",
    "HouseSettings",
    "RoomSettings",
    "LightSettings",
    "EngineInput",
    "Solution",
    "RemoteSettings",
    "DEFAULT_LUX_CURVE",
    "DEFAULT_LUX_CLOUDY_CURVE",
    "DEFAULT_BRIGHTNESS_TIMELINE",
    "DEFAULT_COLOUR_TIMELINE",
    "DEFAULT_SUNRISE_CURVE",
    "DEFAULT_SUNSET_CURVE",
]


class Family(str, Enum):
    """Bulb families with distinct Zigbee hardware rate and serialisation capabilities."""

    AQARA_RGB = "aqara_rgb"
    AQARA_CCT = "aqara_cct"
    IKEA = "ikea"


class Mode(str, Enum):
    """Engine operating modes."""

    NORMAL = "normal"
    NIGHT = "night"
    AWAY = "away"
    SUNRISE = "sunrise"
    SUNSET = "sunset"


@dataclass(frozen=True, slots=True)
class RampPoint:
    """One point on the evening ramp."""

    hour: float
    stops: float


DEFAULT_LUX_CURVE: tuple[SplinePoint, ...] = (
    SplinePoint(0.0, 1.0),
    SplinePoint(1.0, 1.0),
    SplinePoint(10.0, 0.6338),
    SplinePoint(40.0, 0.4134),
    SplinePoint(49.0, 0.3819),
    SplinePoint(100.0, 0.2662),
    SplinePoint(540.0, 0.0),
)

DEFAULT_LUX_CLOUDY_CURVE: tuple[SplinePoint, ...] = (
    SplinePoint(0.0, 1.0),
    SplinePoint(50.0, 0.95),
    SplinePoint(500.0, 0.70),
    SplinePoint(2500.0, 0.40),
    SplinePoint(7000.0, 0.20),
    SplinePoint(12000.0, 0.0),
)

DEFAULT_BRIGHTNESS_TIMELINE: tuple[SplinePoint, ...] = (
    SplinePoint(0.0, 254.0),
    SplinePoint(6.5, 254.0),
    SplinePoint(20.0, 254.0),
    SplinePoint(22.5, 254.0),
    SplinePoint(24.0, 254.0),
)

DEFAULT_COLOUR_TIMELINE: tuple[SplinePoint, ...] = (
    SplinePoint(0.0, 2200.0),
    SplinePoint(7.0, 2700.0),
    SplinePoint(12.0, 4000.0),
    SplinePoint(19.0, 3000.0),
    SplinePoint(22.5, 2200.0),
    SplinePoint(24.0, 2200.0),
)

DEFAULT_SUNRISE_CURVE: tuple[SplinePoint, ...] = (
    SplinePoint(0.0, 0.0),
    SplinePoint(30.0, 15.0),
    SplinePoint(70.0, 90.0),
    SplinePoint(100.0, 180.0),
)

DEFAULT_SUNSET_CURVE: tuple[SplinePoint, ...] = (
    SplinePoint(0.0, 180.0),
    SplinePoint(30.0, 120.0),
    SplinePoint(70.0, 40.0),
    SplinePoint(100.0, 0.0),
)



@dataclass(frozen=True, slots=True)
class MasterOutput:
    """The baseline generated by Master Processing before room/fixture post-processing."""

    target_brightness: int
    target_kelvin: int
    demand: float
    time_brightness_level: int
    cloud_coverage: float | None = None
    cloud_alpha: float = 0.0
    demand_clear: float = 0.0
    demand_cloudy: float = 0.0
    trace: tuple[tuple[str, object], ...] = field(default=())


@dataclass(frozen=True, slots=True)
class StateTable:
    """Pre-computed brightness & colour levels for all operating tiers."""

    l1: int
    """Occupancy active level (brightest automatic level)."""
    l2: int
    """Diminished subzone level (relative to L1 in stops)."""
    l3: int
    """Ambience resting floor (fixed level per room)."""
    ls: int
    """Housewide Night Mode level."""
    target_kelvin: int
    """Target colour temperature."""


@dataclass(frozen=True, slots=True)
class HouseSettings:
    """House-wide settings."""

    # -- Master Processing: Splines & Curves --------------------------------------
    lux_curve: tuple[SplinePoint, ...] = DEFAULT_LUX_CURVE
    lux_cloudy_curve: tuple[SplinePoint, ...] = DEFAULT_LUX_CLOUDY_CURVE
    cloudy_blend_threshold: float = 50.0
    brightness_timeline: tuple[SplinePoint, ...] = DEFAULT_BRIGHTNESS_TIMELINE
    colour_timeline: tuple[SplinePoint, ...] = DEFAULT_COLOUR_TIMELINE
    mood_trim_stops: float = 0.0

    # -- Master Processing: Legacy compatibility fields ---------------------------
    lux_full: float = 1.0
    lux_window: float = 539.0
    ramp: tuple[RampPoint, ...] = (
        RampPoint(hour=20.0, stops=-0.5),
        RampPoint(hour=22.5, stops=-1.5),
    )
    morning_release_hour: float = 6.5
    evening_axis_hour: float = 15.0
    ramp_onset_minutes: float = 30.0
    morning_glide_minutes: float = 90.0
    bias_stops: float = 0.0

    # -- Ambience Gate & Night ----------------------------------------------------
    ambience_start_lux: float = 50.0
    ambience_stop_lux: float = 80.0
    ambience_debounce_falling_s: float = 0.0
    ambience_debounce_rising_s: float = 0.0
    ambience_level: int = 0
    ambience_ignores_occupancy: bool = True
    demand_floor_level: int = 1

    night_level: int = 3
    night_kelvin: int = 2200
    night_release_lux: float = 10.0
    alarm_lead_minutes: float = 30.0
    alarm_stale_minutes: float = 120.0

    # -- Cutoffs & Limits ---------------------------------------------------------
    min_cutoff: int = 1
    rate_limit_step: int = 0
    dead_zone: int = 2

    # -- The 7 Transitions Matrix -------------------------------------------------
    transition_up_occupancy_s: float = 2.0
    transition_up_ambience_s: float = 10.0
    transition_down_diminish_s: float = 5.0
    transition_down_ambience_s: float = 5.0
    transition_down_off_s: float = 4.0
    transition_automatic_s: float = 15.0
    transition_manual_s: float = 0.5

    # -- Colour Settings ----------------------------------------------------------
    day_kelvin: int = 4000
    colour_heartbeat_s: float = 600.0
    colour_trim_kelvin: int = 0
    colour_step_mired: int = 5
    colour_step_mired_smooth: int = 2
    colour_catch_up_steps: int = 3
    colour_step_transition_s: float = 4.0
    colour_rate_floor: float = 0.156
    colour_rate_safety: float = 1.5

    # -- Adaptive Interval & Hardware Thresholds ----------------------------------
    update_interval_min_s: float = 30.0
    update_interval_home_s: float = 150.0
    update_interval_max_s: float = 600.0
    lux_volatility_lx: float = 50.0
    refresh_debounce_s: float = 0.3
    dusk_fallback_hour: float = 21.5
    lux_history_samples: int = 5
    manual_brightness_threshold: int = 25
    manual_kelvin_threshold: int = 100
    fallback_min_kelvin: int = 2000
    fallback_max_kelvin: int = 9009
    family_cct_max_kelvin: int = 4200
    family_rgb_max_kelvin: int = 7000

    # -- The 3 Bedroom Special Modes ----------------------------------------------
    bedroom_sleep_forced_off: bool = True
    sunrise_fade_enabled: bool = True
    sunrise_fade_minutes: float = 30.0
    virtual_sunrise_target_level: int = 180
    sunrise_curve: tuple[SplinePoint, ...] = DEFAULT_SUNRISE_CURVE
    sunset_fade_enabled: bool = True
    sunset_fade_minutes: float = 20.0
    sunset_dwell_minutes: float = 5.0
    sunset_curve: tuple[SplinePoint, ...] = DEFAULT_SUNSET_CURVE
    bedtime_dwell_enabled: bool = True
    bedtime_dwell_hour: float = 22.5
    bedtime_dwell_level: int = 15

    # -- Display Only -------------------------------------------------------------
    gamma: float = 2.39


@dataclass(frozen=True, slots=True)
class RemoteSettings:
    """Physical remote controller button mappings."""

    remote_id: str
    name: str = "Remote"
    room_id: str = ""
    action_entity: str = ""
    button_on: str = "toggle_auto_manual"
    button_off: str = "turn_off"
    button_up: str = "nudge_bias_up"
    button_down: str = "nudge_bias_down"
    button_left: str = "toggle_manual"
    button_right: str = "toggle_sleep"


@dataclass(frozen=True, slots=True)
class ZoneSettings:
    """Sub-zone inside an area (e.g. Kitchen Diner, Living Office)."""

    zone_id: str = ""
    name: str = "Zone"
    lights: tuple[str, ...] = ()
    bias_stops: float = 0.0
    diminish_stops: float = 0.0
    diminish_pct: float = 40.0


@dataclass(frozen=True, slots=True)
class RoomSettings:
    """Per-Area settings (an area is four walls)."""

    name: str = "Room"
    bias_stops: float = 0.0
    zone_bias_stops: float = 0.0
    diminish_stops: float = 0.0
    diminish_pct: float = 40.0
    ambience_level: int = 0
    night_off: bool = False
    manual_hold_minutes: float = 30.0
    manual_mode: bool = False
    sunrise_enabled: bool = False
    sunset_enabled: bool = False
    bedtime_dwell_enabled: bool = False
    zones: tuple[ZoneSettings, ...] = ()


@dataclass(frozen=True, slots=True)
class LightSettings:
    """Per-fixture hardware settings."""

    entity_id: str = ""
    family: Family = Family.AQARA_RGB
    bias_stops: float = 0.0
    clamp_min: int = 0
    clamp_max: int = 254
    min_kelvin: int = 2000
    max_kelvin: int = 9009


@dataclass(frozen=True, slots=True)
class EngineInput:
    """Inputs read for one evaluation tick."""

    lux: float
    occupied: bool
    dnd: bool
    clock_hour: float
    night_active: bool = False
    asleep: bool = False
    away: bool = False
    sunrise_progress: float | None = None
    sunset_progress: float | None = None
    bedtime_dwell_active: bool = False
    ambience_open: bool = True
    ambience_resolved: bool | None = None
    diminish_active: bool = False
    manual_level: int | None = None
    manual_mode: bool = False
    current_level: int = 0
    last_written_level: int | None = None
    last_source: str | None = None
    cloud_coverage: float | None = None


@dataclass(frozen=True, slots=True)
class Solution:
    """The engine's computed solution for one light."""

    level: int
    should_write: bool
    mode: Mode
    ambience_open: bool
    demand: float
    stops: float
    fraction: float
    source: str = "demand"
    state_table: StateTable | None = None
    trace: tuple[tuple[str, object], ...] = field(default=())

    def with_trace(self, step: str, value: object) -> Solution:
        return replace(self, trace=(*self.trace, (step, value)))
