// Build the panel into the integration.
//
// The output is COMMITTED. HACS copies files, it never runs a build, so an un-built
// tree installs as a blank sidebar page. `panel.py` logs loudly if the bundle is
// missing, but the real fix is to remember to run this before committing.

import { build, context } from "esbuild";
import { mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outfile = resolve(here, "../custom_components/solace/frontend/solace-panel.js");
mkdirSync(dirname(outfile), { recursive: true });

/** @type {import("esbuild").BuildOptions} */
const options = {
  entryPoints: [resolve(here, "src/solace-panel.ts")],
  outfile,
  bundle: true,
  format: "esm",
  // HA serves panels to modern browsers only; targeting lower would only bloat the
  // bundle and pull in polyfills the host already has.
  target: "es2021",
  minify: true,
  sourcemap: false,
  legalComments: "none",
  banner: {
    js: "/* Solace lighting panel — generated by panel/build.mjs. Do not edit by hand. */",
  },
};

if (process.argv.includes("--watch")) {
  const ctx = await context(options);
  await ctx.watch();
  console.log("watching…");
} else {
  const result = await build({ ...options, metafile: true });
  const bytes = Object.values(result.metafile.outputs)[0].bytes;
  console.log(`built ${outfile} (${(bytes / 1024).toFixed(1)} kB)`);
}
